"'SHS Configuration' As screen":

    SHSConfigComp As Component1:
        CurrentScreen: ="Configuration"
        Height: =768

    CanVasContainer_16 As groupContainer.manualLayoutContainer:
        Height: =App.Height-Component1_1.ComHeaderHeight
        Width: =App.Width-Component1_1.VarMenuWidth
        X: =SHSConfigComp.VarMenuWidth
        Y: =Component1_1.ComHeaderHeight
        ZIndex: =7

        Icon13 As icon.HorizontalLine:
            BorderColor: =RGBA(102, 102, 102, 1)
            BorderThickness: =1
            Color: =RGBA(102, 102, 102, 1)
            Height: =1
            Icon: =Icon.HorizontalLine
            PaddingBottom: =10
            PaddingLeft: =10
            PaddingRight: =10
            PaddingTop: =10
            Width: =1039
            X: =52
            Y: =60
            ZIndex: =1

        Label13 As label:
            Color: =RGBA(0, 18, 107, 1)
            FontWeight: =FontWeight.Bold
            Height: =58
            Size: =20
            Text: ="Supplier Happiness Survey Settings"
            Width: =550
            X: =52
            Y: =2
            ZIndex: =2

        Container3 As groupContainer.manualLayoutContainer:
            DropShadow: =DropShadow.Semilight
            Height: =528
            Width: =596
            X: =52
            Y: =84
            ZIndex: =3

        Container4 As groupContainer.manualLayoutContainer:
            DropShadow: =DropShadow.Semilight
            Height: =298
            Width: =355
            X: =702
            Y: =84
            ZIndex: =4

    "'SHSConfig Main' As groupContainer.verticalAutoLayoutContainer":
        Height: =App.Height-SHSConfigComp.ComHeaderHeight
        LayoutDirection: =LayoutDirection.Vertical
        LayoutMode: =LayoutMode.Auto
        Width: =App.Width-SHSConfigComp.VarMenuWidth
        X: =SHSConfigComp.VarMenuWidth
        Y: =SHSConfigComp.ComHeaderHeight
        ZIndex: =8

